# Generated by Django 3.1 on 2023-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_leaf',
            field=models.BooleanField(default=True),
        ),
    ]
