# Generated by Django 5.0.6 on 2024-08-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_node_is_func'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
