version: '3.8'

name: qcalc

services:
  # 1. SSL AUTOMATION
  certbot:
    image: certbot/certbot:v2.11.0
    container_name: certbot
    restart: "no"
    # manual run to generate certificate
    # certbot certonly --webroot --webroot-path=/var/www/certbot --email <your_email> --agree-tos --no-eff-email --cert-name <your_domain> -d <your_domain> -d www.<your_domain>
    # bash does not exist in certbot container
    entrypoint: /bin/sh -c "trap 'exit' TERM; while :; do certbot renew --non-interactive; sleep 12h & wait $${!}; done;"
    volumes:
      - ~/qcalc_dock/.local/certbot/conf:/etc/letsencrypt
      - ~/qcalc_dock/.local/certbot/www:/var/www/certbot
      - ~/qcalc_dock/.local/log/certbot/:/var/log/letsencrypt
    networks:
      - qcnet
    depends_on:
      nginx:
        condition: service_started

  # 2. REVERSE PROXY & ROUTER
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=<your_host_name>
    volumes:
      - ~/qcalc_dock/.local/nginx/templates:/etc/nginx/templates
      - ~/qcalc_dock/.local/nginx/conf:/etc/nginx/conf.d
      - ~/qcalc_dock/.local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/qcalc_dock/.local/certbot/conf:/etc/letsencrypt
      - ~/qcalc_dock/.local/certbot/www:/var/www/certbot
      - ~/qcalc_dock/.local/log/nginx:/var/log/nginx
      # check nginx location /static/, the path should be consistent
      - static:/usr/src/qcalc_dock/qcalc/staticfiles/
    networks:
      - qcnet
    depends_on:
      qcalc:
        condition: service_started

  # 3. ONE-TIME MIGRATION WORKER
  qcalc_init:
    image: qcalc
    build:
      context: ~/qcalc_dock
      dockerfile: Dockerfile
    container_name: qcalc_migration_runner
    restart: "no"
    command: >
      bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate
      "
    volumes:
      - ~/qcalc_dock/qcalc:/usr/src/qcalc_dock/qcalc
      - ~/qcalc_dock/qcalc_res:/usr/src/qcalc_dock/qcalc_res
      - static:/usr/src/qcalc_dock/qcalc/staticfiles/
    networks:
      - qcnet
    depends_on:
      redis:
        condition: service_started
#      memcached:
#        condition: service_started
      postgres:
        condition: service_started
#     mysql:
#       condition: service_started


  # 4. SCALABLE WEB SERVICE (REPLICAS)
  qcalc:
    image: qcalc
    restart: always
    deploy:
      replicas: 3
    environment:
      - GUNICORN_INSTANCE_ID=${HOSTNAME:-qcalc_web_node}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 900
    volumes:
      - ~/qcalc_dock/qcalc:/usr/src/qcalc_dock/qcalc
      - ~/qcalc_dock/qcalc_res:/usr/src/qcalc_dock/qcalc_res
      - ~/qcalc_dock/.cache:/usr/src/qcalc_dock/.cache
      - ~/qcalc_dock/.temp:/usr/src/qcalc_dock/.temp
      - ~/qcalc_dock/.local/log/qcalc:/usr/src/qcalc_dock/.local/log/qcalc
      - ~/qcalc_dock/.local/log/gunicorn:/var/log/gunicorn
      - static:/usr/src/qcalc_dock/qcalc/staticfiles/
    networks:
      - qcnet
    depends_on:
      qcalc_init:
        condition: service_completed_successfully
      redis:
        condition: service_started
#      memcached:
#        condition: service_started
      postgres:
        condition: service_started
#     mysql:
#       condition: service_started

  # 5. CACHE ENGINE: MEMCACHED
  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    restart: unless-stopped
    command: memcached -m 256
    networks:
      - qcnet

  # 6. DATABASE ENGINE: POSTGRESQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=qcalc
      - POSTGRES_PASSWORD=<pg_user_password>
      - POSTGRES_DB=qcalc
    networks:
      - qcnet

# --- EXTRA SERVICE ALTERNATIVES (UNCOMMENT TO USE) ---
#  redis:
#    image: redis:8
#    container_name: redis
#    restart: unless-stopped
#    networks:
#      - qcnet

#  mysql:
#    image: mysql:8.4
#    container_name: mysql
#    restart: unless-stopped
#    volumes:
#      - mysqldata:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: <mysql_root_password>
#      MYSQL_DATABASE: qcalc
#      MYSQL_USER: qcalc
#      MYSQL_PASSWORD: <mysql_user_password>
#    networks:
#      - qcnet

networks:
  qcnet:
    driver: bridge
    name: qcnet

volumes:
  pgdata:
    name: pgdata
#  mysqldata:
#    name: mysqldata
  static:
    name: static
