# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 Debasish C Saha

from qcore.mod_anno import *


def demo_input__info():
    ptrn = r'^\w{3,5}$'
    return {
        'title': 'Testing Various Input Types',
        'schema': {
            'tbool': {'help_text': 'Boolean input.'},
            'tchar': {
                'help_text': 'Short character input.',
                'attrs': {'placeholder': 'Enter a short string'},
            },
            'tcheckbox': {'help_text': 'Checkbox input.'},
            'tcheckboxselectmultiple': {
                'choices': ['A', 'B', 'C'],
                'help_text': 'Multiple checkbox choices.',
            },
            'tchoice': {
                'choices': ['A', 'B', 'C'],
                'help_text': 'Single select choice.',
            },
            'tdate': {'help_text': 'Date input.'},
            'tdatetime': {'help_text': 'Date and time input.'},
            'tdecimal': {'help_text': 'Decimal number input.'},
            'tduration': {'help_text': 'Duration input.'},
            'temail': {
                'help_text': 'Email address input.',
                'attrs': {'placeholder': 'Enter a valid email'}
            },
            'tfloat': {'help_text': 'Floating-point number input.'},
            'tinteger': {'help_text': 'Integer input.'},
            'tmultiplechoice': {
                'choices': ['A', 'B', 'C'],
                'help_text': 'Multiple select choices.',
            },
            'tqty1': {'help_text': 'Quantity input with a unit.'},
            'tqty2': {'help_text': 'Quantity input with a unit.'},
            'tqty3': {'help_text': 'Multi-part quantity input.'},
            'tqlist': {'help_text': 'Dynamic list input.'},
            'tradio': {
                'choices': ['A', 'B', 'C'],
                'help_text': 'Radio-button choice.',
            },
            'trange': {
                'attrs': {'step': '1', 'min': '1', 'max': '10'},
                'help_text': 'Range input from 1 to 10.',
            },
            'tread': {'help_text': 'Read-only text input.'},
            'tselect2': {
                'choices': ['A', 'B', 'C'],
                'help_text': 'Enhanced select input.',
            },
            'tstring': {'help_text': 'Text string input.'},
            'ttable': {'help_text': 'Editable table input.'},
            'ttext': {'help_text': 'Text input.'},
            'ttextarea': {'help_text': 'Multi-line text input.'},
            'ttime': {'help_text': 'Time input.'},
            'tuom2': {'help_text': 'Compatible unit select input.'},
            'tuom': {'help_text': 'Compatible unit input.'},
            'tuomx': {'help_text': 'Any valid unit input.'},
            'turl': {'help_text': 'URL input.'},
        },
        'outcol': 'result'
    }


def demo_input(  # 48 types - 18
    tbool: bool = True,
    # tbtn: bool,
    tchar: qchar = 'Hello',
    tcheckbox: 'checkbox' = True,
    tcheckboxselectmultiple: 'checkboxselectmultiple' = ['A', 'C'],
    tchoice: 'choice' = 'B',
    # tcombo:'combo',
    tdate: qdate = '1971-12-16',
    tdatetime: qdatetime = '1971-12-15 23:59:59',
    tdecimal: 'decimal' = 100.50,
    tduration: 'duration' = 20,
    temail: qemail = 'somebody@example.com',
    # tfile: qfile = None,
    # tfilepath: 'filepath' = '/home/guest/',
    tfloat: float = 5.67,
    # tgenericipaddress:'genericipaddress'='192.168.0.11',
    # thidden:'hidden'='Gem',
    # thtml: qhtml = 'Hello World',
    # timage: 'image' = None,
    tinteger: int = 123,
    tmultiplechoice: 'multiplechoice' = ['B', 'C'],
    # tmultivalue: 'multivalue' = None,
    # tnullboolean: 'nullboolean' = None,
    tqty1='1 ft',
    tqty2='5 kg',
    tqty3='23yd, 2ft, 6inch',
    tqlist: qlist[qchar] = ['A', 'B', 'C'],
    tradio: 'radio' = 'A',
    trange: 'range' = 5,
    # trchoice: 'rchoice' = '?',
    tread: qread = 'Read Only',
    # tpattern: qchar = 'hi',
    # tregex: qregex = 'hi',
    tselect2: qsel2 = 'B',
    # tslug: 'slug' = '?',
    # tsplitdatetime: 'splitdatetime' = '?',
    tstring: str = 'A string',
    ttable: qtable = pd.DataFrame({'Name': ['Dave', 'Arche', 'Mom']}),  # default multichoice!?
    ttext: qtext = 'Some texts',
    ttextarea: qtexta = 'Some more texts',
    ttime: qtime = '23:59:59',
    # ttypedchoice:typedchoice='?',
    # ttypedmultiplechoice:typedmultiplechoice='?'
    tuom2: quom2 = 'm',
    tuom: quom = 'ft',
    tuomx: quomx = 'kg',
    turl: qurl = 'https://www.google.com',
    # tuuid: 'uuid'='?',
):
    return {
        'tbool': tbool,
        'tchar': tchar,
        'tcheckbox': tcheckbox,
        'tcheckboxselectmultiple': tcheckboxselectmultiple,
        'tchoice': tchoice,
        # 'tpattern': tpattern,
        'tdate': tdate,
        'tdatetime': tdatetime,
        'tdecimal': tdecimal,
        'tduration': tduration,
        'temail': temail,
        # 'tfile': tfile,
        'tfloat': tfloat,
        'tinteger': tinteger,
        'tmultiplechoice': tmultiplechoice,
        # page: page,
        'tqty1': tqty1,
        'tqty2': tqty2,
        'tqty3': tqty3,
        'tqlist': tqlist,
        'tradio': tradio,
        'trange': trange,
        'tread': tread,
        # 'tregex': tregex,
        'tselect2': tselect2,
        'tstring': tstring,
        'ttable': ttable,
        'ttext': ttext,
        'ttextarea': ttextarea,
        'ttime': ttime,
        'tuom2': tuom2,
        'tuom': tuom,
        'tuomx': tuomx,
        'turl': turl,
        # 'tuuid': tuuid,
    }
