# Generated by Django 5.0.6 on 2024-08-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystuff',
            name='item',
            field=models.JSONField(),
        ),
    ]
