# Generated by Django 5.0.6 on 2024-10-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_mystuff_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=10)),
                ('item_id', models.CharField(db_index=True, max_length=50)),
                ('variant_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('item', models.JSONField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('changed_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mystuff',
            name='changed_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mystuff',
            name='item_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mystuff',
            name='object_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='mystuff',
            index=models.Index(fields=['user', 'object_id', 'item_id'], name='calc_mystuf_user_id_72fdc6_idx'),
        ),
        migrations.AddField(
            model_name='myinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myinputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='myinput',
            index=models.Index(fields=['user', 'object_id', 'item_id', 'variant_id'], name='calc_myinpu_user_id_4a559c_idx'),
        ),
        migrations.AddConstraint(
            model_name='myinput',
            constraint=models.UniqueConstraint(fields=('user', 'object_id', 'item_id', 'variant_id'), name='unique_user_item_variant'),
        ),
    ]
