# Generated by Django 5.0.6 on 2024-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_myinput_mystuff_changed_on_alter_mystuff_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinput',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='myinput',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
