# Generated by Django 5.0.6 on 2024-10-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_myinput_access_token_myinput_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystuff',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
