# Generated by Django 5.0.6 on 2024-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_mystuff_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinput',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
