# nginx configuration version nginx.conf-v1.4j
# Rename this file to nginx.conf and copy to ../nginx folder

user  nginx;

# Set the number of worker processes based on the number of CPU cores
worker_processes auto;

# Increase the limit of file descriptors for the NGINX process
worker_rlimit_nofile 8192;

events {
    # Maximum number of simultaneous connections per worker process
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Map invalid HTTP versions for HTTP connections
    map $server_protocol $block_request {
        default 1;                 # Block by default
        "HTTP/1.0" 0;              # Allow HTTP/1.0
        "HTTP/1.1" 0;              # Allow HTTP/1.1
        "HTTP/2" 0;                # Allow HTTP/2
    }

    # Enable Gzip compression for various content types
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_vary on;
	# Add a limit for compression to avoid compressing very small files
	gzip_min_length 1024;

    # Keepalive settings to reuse connections efficiently
	# Maximum time for an idle client connection to be kept open on the server
	# Mandatory first parameter, default 75s
    keepalive_timeout 65;
	# Limit on the number of requests per live connection
    keepalive_requests 100;

    # Buffer size settings to handle large headers and responses
    client_body_buffer_size 128k;
	# Limit for the /upload file size
    client_max_body_size 50M;
    client_header_buffer_size 1k;
    large_client_header_buffers 4 4k;

    # Enable Asynchronous I/O (AIO) for better file I/O performance
    aio on;
    directio 4m;
    output_buffers 1 512k;

    # Customize log format for better insights and reduced I/O
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';

    # Optimize access log with buffer and flush settings
    access_log /var/log/nginx/access.log main buffer=32k flush=5m;

    # Limits file transfer chunks to 1 Megabytes
    sendfile        on;
    sendfile_max_chunk 1m;
    #tcp_nopush     on;

    # Limit request rate to prevent DDoS attacks
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    include /etc/nginx/conf.d/*.conf;
}
