# Generated by Django 5.0.6 on 2026-08-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_publish_calculator', 'Can publish calculator')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
